### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by SpaceRiceBowl** [Arcaratus/BloodArsenal#101]
http://i.imgur.com/OiMD80u.png

There seems to be a number of missing textures in the newest 1.10.2 update

**Comment by MasterFee** [comment]
Also some blocks like the Stasis Plate crash the game when you place them

Crash log: https://pastebin.com/uUXMYFSC

**Comment by Arcaratus** [comment]
After hours of being dumb, both issues should now be fixed in the latest 1.10.2 version!

**Comment by MasterFee** [comment]
Placing the stasis plate still crashes the game :/

Crash log: https://pastebin.com/CWMrjUdE

**Comment by Arcaratus** [comment]
Should be fixed in the *latest* version

**Comment by MasterFee** [comment]
Sorry for disappointing you but the game still crashes on block placement :/
This time it's placing down a Blood Infused Wood Slab block

Crash log: https://pastebin.com/CxLSLjAJ
