### ISSUE TITLE
rendering crash with Augmented Holding Sigil (1.10.2-2.1.0-21)

### ISSUE THREAD

**Issue by dualinfinities** [Arcaratus/BloodArsenal#107]
https://gist.github.com/dualinfinities/a07455c65a53c1752d49cf1ba66c29aa

**Comment by Arcaratus** [comment]
Should now be fixed in the latest version

**Comment by dualinfinities** [comment]
sweet.

**Comment by dualinfinities** [comment]
uh, just tested it with 1.10.2-2.1.0-22 still crashing, this time with freeze-y ticking player issue: https://gist.github.com/dualinfinities/11705fd6d1c767144959a0dc1d76ffea
if this isn't the latest version you meant, sorry. it does seem to be a different issue, though.

**Comment by Arcaratus** [comment]
Nothing in the crash log points to Blood Arsenal... are you sure it's because of the Sigil?

**Comment by dualinfinities** [comment]
yep. every time I create one of them through any means, my game freezes immediately. I mean, it could theoretically be another mod tripping over the Sigil, but the Blood Magic one is perfectly fine.

**Comment by dualinfinities** [comment]
I'll try updating forge, that might be the issue.

**Comment by dualinfinities** [comment]
nope, updated Forge to .2422, still freezes.
